# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZDDKrT0xV9Jr4BkSP2C4On65t15Ml-Mp
"""

import pandas as pd

pd.set_option('display.max_columns', None)

compras = pd.read_csv('VendasGrano_csv.csv', encoding='latin1', delimiter=';')

print(compras.head())

empresas_fornecedores = compras['Fornecedor'].drop_duplicates()
print(empresas_fornecedores)

frequencia_fornecedores = compras['Fornecedor'].value_counts()
print(frequencia_fornecedores)

produtos_umehara = compras[compras['Fornecedor'] == 'UMEHARA ALIMENTOS LTDA']['Descrição Material'].unique()
print(produtos_umehara)

produtos_hortifruti_genesis = compras[compras['Fornecedor'] == 'Hortifruti Genesis Ltda']['Descrição Material'].unique()
print(produtos_hortifruti_genesis)

produtos_unidos = compras[compras['Fornecedor'] == 'Supermercados unidos (pai da luiza)']['Descrição Material'].unique()
print(produtos_unidos)

def itens_semelhantes(compras, top_fornecedores):
    compras_fornecedores = compras[compras['Fornecedor'].isin(top_fornecedores)]
    produtos_por_fornecedor = compras_fornecedores.groupby(['Descrição Material', 'Fornecedor']).size().reset_index(name='Quantidade_Compras')
    produtos_por_quantidade_fornecedores = produtos_por_fornecedor.groupby('Descrição Material').size().reset_index(name='Quantidade_Fornecedores')
    produtos_com_mais_de_um_fornecedor = produtos_por_quantidade_fornecedores[produtos_por_quantidade_fornecedores['Quantidade_Fornecedores'] > 1]['Descrição Material']

    for produto in produtos_com_mais_de_um_fornecedor:
        print('Produto:', produto)
        fornecedores_produto = produtos_por_fornecedor[produtos_por_fornecedor['Descrição Material'] == produto]
        for index, row in fornecedores_produto.iterrows():
            fornecedor = row['Fornecedor']
            quantidade_compras = row['Quantidade_Compras']
            print('  Fornecedor:', fornecedor)
            print('  Quantidade de compras:', quantidade_compras)
        print()

top_fornecedores = ['UMEHARA ALIMENTOS LTDA', 'Hortifruti Genesis Ltda', 'Supermercados unidos (pai da luiza)']
itens_semelhantes(compras, top_fornecedores)
