# -*- coding: utf-8 -*-
"""ProjetoBigData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGQb9He5nwwRkzK1Z_Gf_Q47FNwsizI8
"""

import pandas as pd

vendas = pd.read_csv('VendasGrano.csv', encoding='latin1', delimiter=';')

vendas.head()

vendas.loc[[0, 1, 2]]

vendas.loc['UMEHARA ALIMENTOS LTDA']

vendas.loc[['Laranja', 'Melancia'], ['Qtde.', 'Data de Emissão']]